import type { Metadata } from "next";
import { Sora, Space_Grotesk, Source_Code_Pro } from "next/font/google";
import "./globals.css";

const sora = Sora({ subsets: ["latin"], variable: '--font-sora' });
const spaceGrotesk = Space_Grotesk({ subsets: ["latin"], variable: '--font-space-grotesk' });
const sourceCodePro = Source_Code_Pro({ subsets: ["latin"], variable: '--font-code' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.variable} ${spaceGrotesk.variable} ${sourceCodePro.variable} font-sans`}>{children}</body>
    </html>
  );
}
